# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Ingredient.create(name: "Lemon")
Ingredient.create(name: "Ice")
Ingredient.create(name: "Mint")
Ingredient.create(name: "Tequila")
Ingredient.create(name: "Vodka")
Ingredient.create(name: "Rum")
Ingredient.create(name: "Gin")
Ingredient.create(name: "Egg white")
Ingredient.create(name: "Orange juice")
Ingredient.create(name: "Syrup")
Ingredient.create(name: "Whiskey")
Ingredient.create(name: "Lime")
Ingredient.create(name: "Bitters")
Ingredient.create(name: "Coffee liqueur")
Ingredient.create(name: "Champagne")
Ingredient.create(name: "Irish cream")
Ingredient.create(name: "Sambuca")
Ingredient.create(name: "Triple sec")
Ingredient.create(name: "Brandy")
Ingredient.create(name: "Bourbon")
Ingredient.create(name: "Cognac")
Ingredient.create(name: "Sambuca")
Ingredient.create(name: "Sprite")

Cocktail.create(name: "Whiskey Sour")
Cocktail.create(name: "Mojito")
Cocktail.create(name: "Manhattan")
Cocktail.create(name: "Dry Martini")
Cocktail.create(name: "Margarita")
Cocktail.create(name: "Pina Colada")
Cocktail.create(name: "Sex on the Beach")
Cocktail.create(name: "Old Fashioned")
Cocktail.create(name: "Spritz")
