# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

lemon = Ingredient.create(name: "Lemon")
ice = Ingredient.create(name: "Ice")
mint = Ingredient.create(name: "Mint")
tequila = Ingredient.create(name: "Tequila")
vodka = Ingredient.create(name: "Vodka")
rum = Ingredient.create(name: "Rum")
gin = Ingredient.create(name: "Gin")
egg = Ingredient.create(name: "Egg white")
orange = Ingredient.create(name: "Orange juice")
syrup = Ingredient.create(name: "Syrup")
whiskey = Ingredient.create(name: "Whiskey")
lime = Ingredient.create(name: "Lime juice")
bitters = Ingredient.create(name: "Bitters")
coffee = Ingredient.create(name: "Coffee liqueur")
champagne = Ingredient.create(name: "Champagne")
irish = Ingredient.create(name: "Irish cream")
sambuca = Ingredient.create(name: "Sambuca")
triple = Ingredient.create(name: "Triple sec")
brandy = Ingredient.create(name: "Brandy")
bourbon = Ingredient.create(name: "Bourbon")
cognac = Ingredient.create(name: "Cognac")
sambuca = Ingredient.create(name: "Sambuca")
vermouth = Ingredient.create(name: "Vermouth")

Cocktail.create(name: "Whiskey Sour")
Dose.create!(description:"2 ounces", cocktail: Cocktail.last, ingredient: bourbon)
Dose.create!(description:"3/4 ounces", cocktail: Cocktail.last, ingredient: syrup)
Dose.create!(description:"3/4 ounces", cocktail: Cocktail.last, ingredient: lemon)
Dose.create!(description:"1 dash", cocktail: Cocktail.last, ingredient: egg)
Cocktail.create(name: "Mojito")
Dose.create!(description:"1 1/2 ounces", cocktail: Cocktail.last, ingredient: rum)
Dose.create!(description:"6 leaves", cocktail: Cocktail.last, ingredient: mint)
Cocktail.create(name: "Margarita")
Dose.create!(description:"2 ounces", cocktail: Cocktail.last, ingredient: tequila)
Dose.create!(description:"1 ounce", cocktail: Cocktail.last, ingredient: lime)
Cocktail.create(name: "Old Fashioned")
Dose.create!(description:"2 ounces", cocktail: Cocktail.last, ingredient: bourbon)
Dose.create!(description:"2 dashes", cocktail: Cocktail.last, ingredient: bitters)
Cocktail.create(name: "Dry Martini")
Dose.create!(description:"3 ounces", cocktail: Cocktail.last, ingredient: gin)
Dose.create!(description:"1/2 ounces", cocktail: Cocktail.last, ingredient: vermouth)

Cocktail.create(name: "Manhattan")
Cocktail.create(name: "Pina Colada")
Cocktail.create(name: "Sex on the Beach")
Cocktail.create(name: "Spritz")
Cocktail.create(name: "Bloody Mary")
Cocktail.create(name: "Cosmopolitan")

# Cocktail.create(name: "The Forum")
# Cocktail.create(name: "SOCAL")
# Cocktail.create(name: "Witch heart")
# Cocktail.create(name: "Montreal special")
# Cocktail.create(name: "Fire Dragon")

# / / Flaming Lamborghini/ / Raspberry Gin/ /
